# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Whiteboard
description: > # this means to ignore newlines until "baseurl:"
  The Whiteboard is a gathering of programmers from around the world
  interested in investigating every aspect of software development.
  Topics range from coffee to software design and everything in between.
  Have you accepted Haskell into your home and into your heart?
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://the-whiteboard.github.io" # the base hostname & protocol for your site
github_username:  the-whiteboard
# twitter_username: stackprogrammer

# Build settings
markdown: kramdown
